# Generated by Django 5.0 on 2025-07-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=255)),
                ('plot', models.TextField()),
                ('director', models.CharField(max_length=255)),
                ('actors', models.TextField()),
                ('language', models.CharField(max_length=100)),
                ('runtime', models.CharField(max_length=50)),
                ('poster', models.URLField()),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
