# Generated by Django 5.0 on 2025-07-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_savedmovie_actors_remove_savedmovie_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedmovie',
            name='category',
            field=models.CharField(choices=[('anime', 'Anime'), ('movie', 'Movie'), ('tvseries', 'TV Series')], max_length=50),
        ),
    ]
